version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    env_file:
      - ./backend/.env
    container_name: portfolio_backend
    environment:
      - PORT=${BACKEND_PORT}
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      network: host
    env_file:
      - ./frontend/.env
    container_name: portfolio_frontend
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
